"""
Population Stability Index (PSI) for every numeric model feature: how far
the live scoring population (current-season players) has drifted from the
population the model was trained on (prior-season stats of transferred
players).

PSI is the standard feature-drift check in credit-risk model monitoring.
Bins are deciles of the training ("expected") distribution; each bin's
share in the live ("actual") population is compared against it:

    PSI = sum over bins of (actual% - expected%) * ln(actual% / expected%)

Common rule of thumb: < 0.10 stable, 0.10-0.25 moderate shift, > 0.25
significant shift. These are conventions, not statistical tests.

Caveat, stated in the report too: the two populations differ by design.
Training rows are players who were later transferred for a disclosed fee;
the live population is every current player with stats. Part of any shift
is that selection effect, not the market changing over time.

Usage:
    python scripts/train/stability_psi.py   # writes docs/stability-psi.md
"""
from __future__ import annotations

import sys
from datetime import date
from pathlib import Path

import numpy as np
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))

EPS = 1e-4  # floor for empty bins so ln() stays finite


def psi(expected: np.ndarray, actual: np.ndarray, n_bins: int = 10) -> float:
    """PSI of `actual` against `expected`, using quantile bins of `expected`.
    NaNs are dropped from both. Features with at most n_bins distinct
    training values are binned by exact value; others use deciles, with
    duplicate edges collapsed (so a count feature with many zeros may get
    fewer than n_bins bins)."""
    expected = np.asarray(expected, dtype=float)
    actual = np.asarray(actual, dtype=float)
    expected = expected[~np.isnan(expected)]
    actual = actual[~np.isnan(actual)]
    if len(expected) == 0 or len(actual) == 0:
        return float("nan")

    distinct = np.unique(expected)
    if len(distinct) <= n_bins:
        # Discrete feature (e.g. a 0/1 flag): one bin per value seen in either
        # population. Quantile edges would collapse into a single bin and
        # always report zero drift.
        values = np.union1d(distinct, np.unique(actual))
        exp_pct = np.array([(expected == v).mean() for v in values])
        act_pct = np.array([(actual == v).mean() for v in values])
    else:
        edges = np.unique(np.quantile(expected, np.linspace(0, 1, n_bins + 1)))
        # Open-ended outer bins so live values outside the training range still count.
        edges[0], edges[-1] = -np.inf, np.inf
        exp_pct = np.histogram(expected, bins=edges)[0] / len(expected)
        act_pct = np.histogram(actual, bins=edges)[0] / len(actual)
    exp_pct = np.clip(exp_pct, EPS, None)
    act_pct = np.clip(act_pct, EPS, None)
    return float(np.sum((act_pct - exp_pct) * np.log(act_pct / exp_pct)))


def label(value: float) -> str:
    if np.isnan(value):
        return "n/a"
    if value < 0.10:
        return "stable"
    if value <= 0.25:
        return "moderate shift"
    return "significant shift"


def main() -> None:
    from app.db import SessionLocal
    from generate_predictions import _FEATURE_COLS, _build_live_features, _latest_season

    matrix_path = REPO_ROOT / "data" / "processed" / "training_matrix.parquet"
    train_df = pd.read_parquet(matrix_path)

    db = SessionLocal()
    try:
        season = _latest_season(db)
        live_df, _ = _build_live_features(db, season, date.today())
    finally:
        db.close()

    rows = []
    for col in _FEATURE_COLS:
        value = psi(train_df[col].to_numpy(), live_df[col].to_numpy())
        rows.append((col, value, label(value)))
        print(f"{col:<18} PSI={value:.3f}  {label(value)}")

    lines = [
        "# Feature stability (PSI)",
        "",
        f"Training population: {len(train_df)} transfers (prior-season stats). "
        f"Live population: {len(live_df)} players with {season.label} stats.",
        "Bins are deciles of the training distribution. Rule of thumb: < 0.10 stable,",
        "0.10-0.25 moderate shift, > 0.25 significant shift.",
        "",
        "| Feature | PSI | Reading |",
        "|---|---|---|",
    ]
    lines += [f"| {c} | {v:.3f} | {lab} |" for c, v, lab in rows]
    lines += [
        "",
        "The two populations differ by design: training rows are players who were",
        "later sold for a disclosed fee, the live population is every current player",
        "with stats. Part of any shift is that selection effect, not market drift.",
        "",
        "Generated by `scripts/train/stability_psi.py`.",
    ]
    out = REPO_ROOT / "docs" / "stability-psi.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"\nWrote {out}")


if __name__ == "__main__":
    sys.path.insert(0, str(REPO_ROOT / "backend"))
    main()
